### ISSUE TITLE
k8s container image build failed !!

### ISSUE THREAD

**Issue by bugbounted** [PussTheCat-org/docker-proxitok-quay#5]
<html>
<body>

workspace is ready.
--
2 | Step 1/6 : FROM php:8-apache
3 | ---> af944036d594
4 | Step 2/6 : WORKDIR /var/www/html
5 | ---> [Warning] Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
6 | ---> Running in 3e0e10f1180c
7 | Removing intermediate container 3e0e10f1180c
8 | ---> 014dcc1b30a9
9 | Step 3/6 : COPY --from=composer /usr/bin/composer /usr/bin/composer
10 | ---> e269c6b9ef13
11 | Step 4/6 : ARG GH_TOKEN
12 | ---> [Warning] Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
13 | ---> Running in e4160b638db3
14 | Removing intermediate container e4160b638db3
15 | ---> e23e03ed8b5c
16 | Step 5/6 : RUN apt update -y && apt upgrade -y && apt install -y --no-install-recommends git libzip-dev && pecl install redis zip && docker-php-ext-enable redis zip && a2enmod rewrite headers && mkdir /cache && chown -R www-data:www-data /cache && rm -rf /var/www/html/* && git clone --depth=1 https://github.com/pablouser1/ProxiTok.git . && composer config -g github-oauth.github.com "$GH_TOKEN" && composer update && composer install --no-interaction --optimize-autoloader --no-dev && apt autoclean -y && apt autoremove -y && rm -rf /var/lib/apt/lists/* && rm -rf /usr/bin/composer
17 | ---> [Warning] Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
18 | ---> Running in 52717e5d7fb8
19 | [91m
20 | [0m[91mWARNING: apt does not have a stable CLI interface. Use with caution in scripts.
21 |  
22 | [0mGet:1 http://security.debian.org/debian-security bullseye-security InRelease [44.1 kB]
23 | Get:2 http://deb.debian.org/debian bullseye InRelease [116 kB]
24 | Get:3 http://deb.debian.org/debian bullseye-updates InRelease [39.4 kB]
25 | Get:4 http://security.debian.org/debian-security bullseye-security/main amd64 Packages [153 kB]
26 | Get:5 http://deb.debian.org/debian bullseye/main amd64 Packages [8182 kB]
27 | Get:6 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [2592 B]
28 | Fetched 8537 kB in 2s (4769 kB/s)
29 | Reading package lists...
30 | Building dependency tree...
31 | Reading state information...
32 | All packages are up to date.
33 | [91m
34 | WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
35 |  
36 | [0mReading package lists...
37 | Building dependency tree...
38 | Reading state information...
39 | Calculating upgrade...
40 | 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
41 | [91m
42 | [0m[91mWARNING: apt does not have a stable CLI interface. Use with caution in scripts.
43 |  
44 | [0mReading package lists...
45 | Building dependency tree...
46 | Reading state information...
47 | The following additional packages will be installed:
48 | git-man libcurl3-gnutls liberror-perl libzip4 zlib1g-dev
49 | Suggested packages:
50 | gettext-base git-daemon-run \| git-daemon-sysvinit git-doc git-el git-email
51 | git-gui gitk gitweb git-cvs git-mediawiki git-svn
52 | Recommended packages:
53 | less ssh-client
54 | The following NEW packages will be installed:
55 | git git-man libcurl3-gnutls liberror-perl libzip-dev libzip4 zlib1g-dev
56 | 0 upgraded, 7 newly installed, 0 to remove and 0 not upgraded.
57 | Need to get 8133 kB of archives.
58 | After this operation, 39.7 MB of additional disk space will be used.
59 | Get:1 http://security.debian.org/debian-security bullseye-security/main amd64 zlib1g-dev amd64 1:1.2.11.dfsg-2+deb11u1 [191 kB]
60 | Get:2 http://deb.debian.org/debian bullseye/main amd64 libcurl3-gnutls amd64 7.74.0-1.3+deb11u1 [338 kB]
61 | Get:3 http://deb.debian.org/debian bullseye/main amd64 liberror-perl all 0.17029-1 [31.0 kB]
62 | Get:4 http://deb.debian.org/debian bullseye/main amd64 git-man all 1:2.30.2-1 [1827 kB]
63 | Get:5 http://deb.debian.org/debian bullseye/main amd64 git amd64 1:2.30.2-1 [5527 kB]
64 | Get:6 http://deb.debian.org/debian bullseye/main amd64 libzip4 amd64 1.7.3-1 [55.4 kB]
65 | Get:7 http://deb.debian.org/debian bullseye/main amd64 libzip-dev amd64 1.7.3-1 [163 kB]
66 | [91mdebconf: delaying package configuration, since apt-utils is not installed
67 | [0mFetched 8133 kB in 0s (63.9 MB/s)
68 | Selecting previously unselected package libcurl3-gnutls:amd64.
69 | (Reading database ... (Reading database ... 5% (Reading database ... 10% (Reading database ... 15% (Reading database ... 20% (Reading database ... 25% (Reading database ... 30% (Reading database ... 35% (Reading database ... 40% (Reading database ... 45% (Reading database ... 50% (Reading database ... 55% (Reading database ... 60% (Reading database ... 65% (Reading database ... 70% (Reading database ... 75% (Reading database ... 80% (Reading database ... 85% (Reading database ... 90% (Reading database ... 95% (Reading database ... 100% (Reading database ... 14119 files and directories currently installed.)
70 | Preparing to unpack .../0-libcurl3-gnutls_7.74.0-1.3+deb11u1_amd64.deb ...
71 | Unpacking libcurl3-gnutls:amd64 (7.74.0-1.3+deb11u1) ...
72 | Selecting previously unselected package liberror-perl.
73 | Preparing to unpack .../1-liberror-perl_0.17029-1_all.deb ...
74 | Unpacking liberror-perl (0.17029-1) ...
75 | Selecting previously unselected package git-man.
76 | Preparing to unpack .../2-git-man_1%3a2.30.2-1_all.deb ...
77 | Unpacking git-man (1:2.30.2-1) ...
78 | Selecting previously unselected package git.
79 | Preparing to unpack .../3-git_1%3a2.30.2-1_amd64.deb ...
80 | Unpacking git (1:2.30.2-1) ...
81 | Selecting previously unselected package libzip4:amd64.
82 | Preparing to unpack .../4-libzip4_1.7.3-1_amd64.deb ...
83 | Unpacking libzip4:amd64 (1.7.3-1) ...
84 | Selecting previously unselected package zlib1g-dev:amd64.
85 | Preparing to unpack .../5-zlib1g-dev_1%3a1.2.11.dfsg-2+deb11u1_amd64.deb ...
86 | Unpacking zlib1g-dev:amd64 (1:1.2.11.dfsg-2+deb11u1) ...
87 | Selecting previously unselected package libzip-dev:amd64.
88 | Preparing to unpack .../6-libzip-dev_1.7.3-1_amd64.deb ...
89 | Unpacking libzip-dev:amd64 (1.7.3-1) ...
90 | Setting up libzip4:amd64 (1.7.3-1) ...
91 | Setting up libcurl3-gnutls:amd64 (7.74.0-1.3+deb11u1) ...
92 | Setting up liberror-perl (0.17029-1) ...
93 | Setting up zlib1g-dev:amd64 (1:1.2.11.dfsg-2+deb11u1) ...
94 | Setting up git-man (1:2.30.2-1) ...
95 | Setting up libzip-dev:amd64 (1.7.3-1) ...
96 | Setting up git (1:2.30.2-1) ...
97 | Processing triggers for libc-bin (2.31-13+deb11u3) ...
98 | downloading redis-5.3.7.tgz ...
99 | Starting to download redis-5.3.7.tgz (275,200 bytes)
100 | .........................................................done: 275,200 bytes
101 | downloading zip-1.20.1.tgz ...
102 | Starting to download zip-1.20.1.tgz (351,117 bytes)
103 | ...done: 351,117 bytes
104 | 31 source files, building
105 | running: phpize
106 | Configuring for:
107 | PHP Api Version: 20210902
108 | Zend Module Api No: 20210902
109 | Zend Extension Api No: 420210902
110 | enable igbinary serializer support? [no] : enable lzf compression support? [no] : enable zstd compression support? [no] : building in /tmp/pear/temp/pear-build-defaultuserKvFnsx/redis-5.3.7
111 | running: /tmp/pear/temp/redis/configure --with-php-config=/usr/local/bin/php-config --enable-redis-igbinary=no --enable-redis-lzf=no --enable-redis-zstd=no
112 | ls: cannot access '.': Operation not permitted
113 | configure: error: working directory cannot be determined
114 | ERROR: `/tmp/pear/temp/redis/configure --with-php-config=/usr/local/bin/php-config --enable-redis-igbinary=no --enable-redis-lzf=no --enable-redis-zstd=no' failed
115 | The command '/bin/sh -c apt update -y && apt upgrade -y && apt install -y --no-install-recommends git libzip-dev && pecl install redis zip && docker-php-ext-enable redis zip && a2enmod rewrite headers && mkdir /cache && chown -R www-data:www-data /cache && rm -rf /var/www/html/* && git clone --depth=1 https://github.com/pablouser1/ProxiTok.git . && composer config -g github-oauth.github.com "$GH_TOKEN" && composer update && composer install --no-interaction --optimize-autoloader --no-dev && apt autoclean -y && apt autoremove -y && rm -rf /var/lib/apt/lists/* && rm -rf /usr/bin/composer' returned a non-zero code: 1

</body>
</html>

**Comment by TheFrenchGhosty** [comment]
That's an issue on your end.
