### ISSUE TITLE
Getting an error when trying to run docker-compose up

### ISSUE THREAD

**Issue by milutinke** [PussTheCat-org/docker-proxitok-quay#6]
Hello, I'm getting an error when trying to run a container with:
```bash
APP_URL='https://proxytok.privhub.space' sudo docker-compose up -d
```

The error:
```
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for volumes: 'proxitok-cache'
Unsupported config option for services: 'proxitok-redis'
```

How I can solve this?

**Comment by TheFrenchGhosty** [comment]
You docker compose version is old, either update or add `version: "3.0"` at the top of the compose file.

**Comment by milutinke** [comment]
Tried `sudo apt update -y && sudo apt upgrade -y`, did not solve the problem.
Adding `version: "3.0"` has solved it.
Thanks.
